### PR TITLE
Replace `GIDGoogleUser` with `SocialService.User` in case .google

### LINKED ISSUE #759: Google sign in without SDK – New accounts lack email in `WPAccount`
I tested creating a new WordPress.com account by signing in without the Google SDK and WordPress iOS crashed. [This](https://github.com/wordpress-mobile/WordPress-iOS/pull/20128) is the branch I was working on.

 Screenshot 2023-03-24 at 3 52 00 pm

The issue, as far as I could trace it, was that when the app created a `LoginEpilogueUserInfo` with the `WPAccount` instance it just loaded from the DB (?!) via `WPAccount.lookupDefaultWordPressComAccount(_:)`, the instance had no `email`.

### PR DESCRIPTION
**Pull request by mokagio**
Closes #759.

As described in #759, the idea with this PR is to remove the Google SDK-dependent type from the `SocialService` `google` `case` associated value and use the pure Swift `SocialService.User` instead. The new type was introduced in #763.

## To test

The code changes here are consumed via unit tests alone. The demo app doesn't read the `loginFields` metadata where `SocialService` lives.

The "real" test for this new code is in the Jetpack/WordPress iOS that uses it https://github.com/wordpress-mobile/WordPress-iOS/pull/20128

---

- [x] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary.

### CODE REVIEW

File: WordPressAuthenticator/Services/SocialService.swift [hunk 1]
```diff
@@ -9,9 +9,16 @@ public enum SocialService {
...
+        switch self {
+        case .google(let user): return user
+        case .apple(let user): return user
+        }
+    }
+
     /// Google's Signup Linked Account
     ///
-    case google(user: GIDGoogleUser)
+    case google(user: User)
```
Comment (mokagio) [inline WordPressAuthenticator/Services/SocialService.swift:21]: `apple` and `google` both have a `User` associated type now.

This kind of makes it backward to have an enum with associated type, we should have a type with an enum property

```swift
struct SocialUser {

  let fullName: String
  let email: String
  let source: SocialUser.Source // .apple, .google, ...
}
```

I've come across other bits of information in some places that could go into this type, such as the token.

I'm skeptical of working on "such a big" rewrite, though. We should be making changes to the auth layer here carefully. Also, I'd like to first remove all the Google-SDK cruft first. The downside is that we'll have to go through at least two major versions. I think it's worth it, though.

File: WordPressAuthenticator/Model/LoginFields.swift [hunk 2]
```diff
@@ -165,7 +165,7 @@ public class LoginFieldsMeta: NSObject {
          requiredMultifactor: Bool = false,
          socialService: SocialServiceName? = nil,
          socialServiceIDToken: String? = nil,
-         googleUser: GIDGoogleUser? = nil,
+         googleUser: SocialService.User? = nil,
          appleUser: SocialService.User? = nil) {
```
Comment (mokagio) [inline WordPressAuthenticator/Model/LoginFields.swift:169]: I wrote it elsewhere already, but it seems to me like these parameters are ripe for consolidation into a single type (`SocialUser`?).

I'm not keen on introducing such a change right now because I'd like to stay focused on removing the Google SDK only. The tradeoff is that we'll have to cycle through two major version changes, but that seems acceptable. It's just a number after all.

Comment (mokagio) [reply WordPressAuthenticator/Model/LoginFields.swift:169]: > I wrote it elsewhere

Elsewhere = [the file after this](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/764/files#r1152489604), 14 hours ago 🤦‍♂️ 🙃 

But hey, at least I'm consistent in the naming suggestion I'm leaving...

File: WordPressAuthenticator/Signin/LoginViewController.swift [hunk 3]
```diff
@@ -425,10 +425,19 @@ extension LoginViewController {
...
-        loginFields.username = googleEmail
+        updateLoginFields(
+            email: googleEmail,
+            username: googleEmail,
+            fullName: googleUser.profile?.name ?? "",
+            googleToken: googleToken
+        )
+    }
+
+    func updateLoginFields(email: String, username: String, fullName: String, googleToken: String) {
```
Comment (crazytonyli) [inline WordPressAuthenticator/Signin/LoginViewController.swift]: This `username` argument is not used, should we get rid of it? Also, any reason adding another `updateLoginFields` function here, rather than do the assignments in the one above?

**Review by crazytonyli — CHANGES_REQUESTED** [review]

File: WordPressAuthenticator/Signin/LoginViewController.swift (hunk 3 above)
Comment (mokagio) [reply WordPressAuthenticator/Signin/LoginViewController.swift]: What I should have done with that `username` parameter was using it in the method and then passing `.email` at callsite. I guess I was trying to cover my basis.

But your observation made me realize the version with the `GIDGoogleUser` input is unused, and this new one is only used by it. So, I removed both of them.

**Review by crazytonyli — APPROVED** [review]

File: WordPressAuthenticator/Signin/LoginViewController.swift (hunk 3 above)
Comment (crazytonyli) [reply WordPressAuthenticator/Signin/LoginViewController.swift]: Yay, more deletions!
